---
- name: Valider et recharger Nginx
  ansible.builtin.shell: nginx -t
  register: config_check
  changed_when: false
  notify: Recharger le service Nginx

- name: Recharger le service Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
